import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import yaml

CommentType = Literal["hash", "markdown", "none"]
Location = Literal["top", "bottom", "none"]


@dataclass
class CommentFormat:
    comment_type: CommentType = "hash"
    location: Location = "top"


default_comment_format = CommentFormat("hash", "top")
custom_file_handling: dict[str, CommentFormat] = {
    ".md": CommentFormat("markdown", "bottom"),
    ".sh": CommentFormat("hash", "bottom"),  # put at bottom to not mess with shebang
    ".json": CommentFormat("none", "none"),
    ".yaml": CommentFormat("none", "none"),
    ".yml": CommentFormat("none", "none"),
}

HEADER = """\
!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 File is managed by a copier template. See .copier-managed-files.yaml for details.

 You are welcome to make changes to this file in your repo if they are custom to your project,
 but if the change should be shared with other projects, please backport it to the template repo.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"""


def get_base_filename(template_filename: str) -> str:
    """Return the destination filename for a template file.

    Handles two cases:
    - Jinja if-check pattern: {% if cond %}actual_filename{% endif %}[.jinja-base]
      The text between %} and {% is the actual destination filename (no suffix stripping needed).
    - Plain template file: README.md.jinja-base → README.md (strip template suffix).
    """
    result = re.findall(r"%\}(.*?)\{%", template_filename, re.DOTALL)
    if result:
        return result[0]
    for suffix in [".jinja-base", ".jinja"]:
        if template_filename.endswith(suffix):
            return template_filename[: -len(suffix)]
    return template_filename


@dataclass
class ProvenanceResult:
    managed_files: list[str] = field(default_factory=list)


def apply_file_markers(
    src_template_directory: Path,
    dst_directory: Path,
) -> ProvenanceResult:
    template_base_names = {get_base_filename(f.name) for f in src_template_directory.glob("**/*") if f.is_file()}
    managed: list[str] = []

    for file in sorted(dst_directory.glob("**/*")):
        if not file.is_file():
            continue
        if file.name not in template_base_names:
            continue

        comment_formatting = custom_file_handling.get(file.suffix, default_comment_format)
        if comment_formatting.comment_type == "hash":
            specific_header = "\n".join(f"#{line}" for line in HEADER.split("\n"))
        elif comment_formatting.comment_type == "markdown":
            specific_header = f"<!--\n{HEADER}\n-->"
        else:
            managed.append(str(file.relative_to(dst_directory)))
            continue

        with Path.open(file, "r+") as f:
            content = f.read()

            # Strip any existing header to allow location migration without duplication.
            # For bottom: strip "\n<header>\n" first (avoids leaving a stray trailing newline),
            # then fall back to "<header>\n" in case it was added without a preceding newline.
            if comment_formatting.location == "top":
                content = content.replace(f"{specific_header}\n", "")
            elif comment_formatting.location == "bottom":
                content = content.replace(f"\n{specific_header}\n", "")
                content = content.replace(f"{specific_header}\n", "")

            f.seek(0)
            f.truncate()
            if comment_formatting.location == "top":
                f.write(specific_header + "\n")
            f.write(content)
            if comment_formatting.location == "bottom":
                f.write("\n" + specific_header + "\n")

        managed.append(str(file.relative_to(dst_directory)))

    managed.sort()
    return ProvenanceResult(managed_files=managed)


def update_manifest(dst_directory: Path, template_src: str, managed_files: list[str]) -> None:
    manifest_path = dst_directory / ".copier-managed-files.yaml"

    existing: dict = {}
    if manifest_path.exists():
        with manifest_path.open() as f:
            existing = yaml.safe_load(f) or {}

    templates: list[dict] = existing.get("templates", [])
    templates = [t for t in templates if t.get("src") != template_src]
    templates.append({"src": template_src, "managed_files": managed_files})

    header_comment = (
        "# Generated by copier — do not edit manually.\n"
        "# Files listed here are managed by upstream copier templates.\n"
        "# Changes to these files should be considered for backporting to the relevant template repo.\n"
    )

    with manifest_path.open("w") as f:
        f.write(header_comment)
        yaml.dump({"templates": templates}, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Add copier provenance markers and manifest")
    parser.add_argument("src_template_dir", type=Path, help="Template source directory")
    parser.add_argument("dst_dir", type=Path, help="Destination directory")
    parser.add_argument("--template-src", default="", help="Template source identifier for the manifest")
    args = parser.parse_args()

    result = apply_file_markers(args.src_template_dir, args.dst_dir)
    update_manifest(args.dst_dir, args.template_src or str(args.src_template_dir), result.managed_files)


if __name__ == "__main__":
    main()
