services:
  devcontainer:
    # added the platform flag to override any local settings since this image is only compatible with linux/amd64.
    platform: linux/amd64
    build: .
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/copier-base-template:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_venv:/workspaces/copier-base-template/.venv
    command: sleep infinity
    ports:
      - "14343:2222"
    environment:
      - AWS_PROFILE=localstack

volumes:
  python_venv: {}
